from enum import Enum


class EventSeverity(str, Enum):
    CRITICAL = "CRITICAL"
    WARNING = "WARNING"
    INFO = "INFO"


class EventType(str, Enum):
    NEW_DEVICE = "NEW_DEVICE"
    DEVICE_OFFLINE = "DEVICE_OFFLINE"

    HIGH_USAGE = "HIGH_USAGE"
    HIGH_BANDWIDTH = "HIGH_BANDWIDTH"

    QUOTA_EXCEEDED = "QUOTA_EXCEEDED"

    INTERFACE_ERROR = "INTERFACE_ERROR"
    UNUSUAL_TRAFFIC = "UNUSUAL_TRAFFIC"

    LOGIN = "LOGIN"
    LOGIN_FAILED = "LOGIN_FAILED"

    RULE_CHANGED = "RULE_CHANGED"

    DEVICE_BLOCKED = "DEVICE_BLOCKED"
    DEVICE_UNBLOCKED = "DEVICE_UNBLOCKED"

    ENGINE_STARTED = "ENGINE_STARTED"
    ENGINE_STOPPED = "ENGINE_STOPPED"

    DATABASE_ERROR = "DATABASE_ERROR"

    BACKUP_STARTED = "BACKUP_STARTED"
    BACKUP_COMPLETED = "BACKUP_COMPLETED"
    BACKUP_FAILED = "BACKUP_FAILED"