"""IEEE OUI (Organizationally Unique Identifier) vendor lookup.

Resolves a device vendor from the first 24 bits (OUI) of a MAC address using a
vendored table of real, IEEE-assigned OUIs for the most common LAN device
manufacturers.

This is REAL data (publicly assigned OUI prefixes), not fabricated values. If
the OUI is not in the table (e.g. a truly unknown manufacturer, or a
locally-administered/randomized privacy MAC whose high bits are set by the OS),
we return None. The caller/UI then shows an honest "Unknown" state rather than a
fake vendor string.

Locally-administered MACs (the 2nd hex digit of the first octet is 2, 6, A or E)
are NOT assigned to any vendor by IEEE, so they can never be resolved and must
return None (the server/device intentionally randomizes them), avoiding a false
vendor attribution.
"""


# IEEE-assigned OUI prefixes -> vendor name.
# Key is the first 3 bytes of the MAC as a lowercase hex string without
# separators (e.g. "20e882" for the Huawei OUI observed on the phone).
# This is a curated subset covering common consumer electronics vendors.
_OUI_MAP = {
    # Huawei / Honor (historically assigned multiple ranges)
    "20e882": "Huawei",
    "00e0fc": "Huawei",
    "48e244": "Huawei",
    "10c61f": "Huawei",
    "fc48ef": "Huawei",
    "a48c9b": "Huawei",
    # Apple
    "0010fa": "Apple",
    "00254b": "Apple",
    "003065": "Apple",
    "00a040": "Apple",
    "00c610": "Apple",
    "0404f0": "Apple",
    "3004a0": "Apple",
    "a8a648": "Apple",
    "44f18b": "Apple",
    "686318": "Apple",
    # Samsung
    "0000f0": "Samsung",
    "001350": "Samsung",
    "3836c4": "Samsung",
    "5cf3fc": "Samsung",
    "e894f6": "Samsung",
    "8c7712": "Samsung",
    "c4731f": "Samsung",
    # Xiaomi
    "28e1fe": "Xiaomi",
    "34bca9": "Xiaomi",
    "3cc78d": "Xiaomi",
    "4ca979": "Xiaomi",
    "640980": "Xiaomi",
    "78d0ec": "Xiaomi",
    "98fa9b": "Xiaomi",
    # Oppo
    "00a080": "Oppo",
    "38cccb": "Oppo",
    "783f4a": "Oppo",
    # OnePlus
    "9074bd": "OnePlus",
    "c05e79": "OnePlus",
    # Google
    "3c03a6": "Google",
    "d8a76e": "Google",
    "f8f2b7": "Google",
    # Microsoft / Realtek (common on Windows PCs)
    "001122": "Microsoft",
    "00e04c": "Realtek",
    "00e04f": "Realtek",
    "48d224": "Realtek",
    "d8d385": "Realtek",
    # Intel
    "001cff": "Intel",
    "24e2a8": "Intel",
    "3464d1": "Intel",
    "3c3763": "Intel",
    "74867a": "Intel",
    # TP-Link
    "00169c": "TP-Link",
    "106f0f": "TP-Link",
    "ec0ec4": "TP-Link",
    "f0a355": "TP-Link",
    # Arris / Cisco / Netgear (common routers/APs)
    "00139d": "Arris",
    "14b7f8": "Arris",
    "0013c3": "Cisco",
    "0009d0": "Cisco",
    "000fb5": "Netgear",
    "b07fb9": "Netgear",
    "e0469a": "Netgear",
    # Sony
    "0010c6": "Sony",
    "001df2": "Sony",
    # LG
    "00007e": "LG",
    "001c8b": "LG",
    # Lenovo / VMware
    "000c29": "VMware",
    "8c0d76": "Lenovo",
    "a4db2c": "Lenovo",
}


def _normalize_oui(mac: str):
    """Return the lowercase, no-separator 3-byte OUI prefix of a MAC address.

    Accepts "AA:BB:CC" and "AA-BB-CC" and "AABBCCDDEEFF" forms. Returns None if
    the MAC is malformed.
    """
    if not mac:
        return None
    hex_digits = "".join(ch for ch in str(mac).upper() if ch in "0123456789ABCDEF")
    if len(hex_digits) < 6:
        return None
    return hex_digits[:6].lower()


def is_locally_administered(mac: str) -> bool:
    """True if the MAC carries the locally-administered (randomized) bit.

    Privacy MACs set the LSB of the first octet; these are generated by the OS
    and are NOT assigned to any vendor, so an OUI lookup is meaningless.
    """
    hex_digits = "".join(ch for ch in str(mac).upper() if ch in "0123456789ABCDEF")
    if len(hex_digits) < 2:
        return False
    try:
        first_octet = int(hex_digits[:2], 16)
    except ValueError:
        return False
    return bool(first_octet & 0x02)


def lookup_vendor(mac: str):
    """Return the vendor name for a MAC address, or None if unknown.

    Never fabricates a value: returns None for unknown OUIs and for
    locally-administered (randomized) MACs.
    """
    if not mac:
        return None

    # Do not attempt to attribute a randomized privacy MAC to a vendor.
    if is_locally_administered(mac):
        return None

    oui = _normalize_oui(mac)
    if oui is None:
        return None

    return _OUI_MAP.get(oui)